CREATE DATABASE ctrl+x;
USE ctrl+x;

-- USER Table
CREATE TABLE USER (
    U_ID INT AUTO_INCREMENT PRIMARY KEY,
    U_FName VARCHAR(255) NOT NULL,
    U_LName VARCHAR(255) NOT NULL,
    U_DOB TIMESTAMP NOT NULL,
    U_Gender VARCHAR(10) NOT NULL,
    U_Email VARCHAR(255) NOT NULL UNIQUE,
    U_Password VARCHAR(255) NOT NULL,
    U_PNumber VARCHAR(11) NOT NULL,
);

-- ADMIN Table (Combining Superadmin and Admin)
CREATE TABLE ADMIN (
    A_ID INT AUTO_INCREMENT PRIMARY KEY,
    A_Name VARCHAR(255) NOT NULL,
    A_Password VARCHAR(255) NOT NULL,
    A_Email VARCHAR(255) NOT NULL UNIQUE,
    A_Level TINYINT(1) NOT NULL CHECK (A_Level IN (0,1)) -- 1 for Superadmin, 0 for Admin
);

-- CATEGORIES Table
CREATE TABLE CATEGORIES (
    C_ID INT AUTO_INCREMENT PRIMARY KEY,
    C_Name VARCHAR(255) NOT NULL,
    C_Style VARCHAR(255) NOT NULL
);

-- PRODUCT Table
CREATE TABLE PRODUCT (
    P_ID INT AUTO_INCREMENT PRIMARY KEY,
    C_ID INT NOT NULL,
    P_Name VARCHAR(255) NOT NULL,
    P_Price DECIMAL(10,2) NOT NULL,
    P_Picture BLOB,
    FOREIGN KEY (C_ID) REFERENCES CATEGORIES(C_ID) ON DELETE CASCADE
);

-- PRODUCT_VARIANTS Table
CREATE TABLE PRODUCT_VARIANTS (
    PV_ID INT AUTO_INCREMENT PRIMARY KEY,
    P_ID INT NOT NULL,
    P_Color VARCHAR(50) NOT NULL,
    P_Size VARCHAR(50) NOT NULL,
    P_Quantity INT NOT NULL,
    FOREIGN KEY (P_ID) REFERENCES PRODUCT(P_ID) ON DELETE CASCADE
);

-- ORDER Table
CREATE TABLE ORDERS (
    O_ID INT AUTO_INCREMENT PRIMARY KEY,
    U_ID INT NOT NULL,
    O_PM VARCHAR(50) NOT NULL, -- Payment Method
    O_Date TIMESTAMP NOT NULL,
    O_Status VARCHAR(50) NOT NULL,
    O_TotalAmount DECIMAL(10,2) NOT NULL,
    O_DC DECIMAL(10,2), -- Delivery Charges
    FOREIGN KEY (U_ID) REFERENCES USER(U_ID) ON DELETE CASCADE
);

-- ORDER_ITEMS Table
CREATE TABLE ORDER_ITEMS (
    OI_ID INT AUTO_INCREMENT PRIMARY KEY,
    O_ID INT NOT NULL,
    P_ID INT NOT NULL,
    OI_Quantity INT NOT NULL,
    OI_Price DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (O_ID) REFERENCES ORDERS(O_ID) ON DELETE CASCADE,
    FOREIGN KEY (P_ID) REFERENCES PRODUCT(P_ID) ON DELETE CASCADE
);

-- ADDRESS Table
CREATE TABLE ADDRESS (
    A_ID INT AUTO_INCREMENT PRIMARY KEY,
    U_ID INT NOT NULL,
    A_Details TEXT NOT NULL,
    A_City VARCHAR(255) NOT NULL,
    A_State VARCHAR(255) NOT NULL,
    A_ZipCode VARCHAR(255) NOT NULL,
    FOREIGN KEY (U_ID) REFERENCES USER(U_ID) ON DELETE CASCADE
);
